create table customer (custid int ,custname varchar(20),custaddress varchar (100))
insert into customer values(1,'prajwal','ajni')
insert into customer values(2,'rajat','nagpur')
insert into customer values(3,'manu','mumbai')
insert into customer values(4,'pari','nasik')
insert into customer values(5,'bhoomi','akola')
insert into customer values(6,'prachi','yavatmal')
insert into customer values(7,'prut','pune')
insert into customer values(8,'avani','banglore')
insert into customer values(9,'amu','hyderabad')
insert into customer values(10,'shruti','usa')
select * from customer
